#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'loc-and-nav','console_scripts','loc_and_nav'
__requires__ = 'loc-and-nav'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('loc-and-nav', 'console_scripts', 'loc_and_nav')()
    )
