explore_node:
  ros__parameters:
    robot_base_frame: base_link
    costmap_topic: /global_costmap/costmap
    costmap_updates_topic: /global_costmap/costmap_updates
    visualize: false
    planner_frequency: 20.0 #0.15
    progress_timeout: 5.0 #30.0
    potential_scale: 5.0 #3.0
    orientation_scale: 0.0 #0.0
    gain_scale: 1.0 #1.0
    transform_tolerance: 0.3 #0.3
    min_frontier_size: 0.03 #0.5
